//! Naming of static font targets.
//!
//! The Python builder derives these names from the designspace
//! `<instance filename="...">` attribute, which is only trustworthy when the
//! designspace was generated by glyphsLib; a hand-written designspace may put
//! anything there, and a bare UFO has no such attribute at all.
//!
//! We derive the name from the instance's own names instead, following the
//! convention that a style name carries only weight and italic variation, with
//! any other axis variation folded into the family name: `UbuntuSansCondensed-Bold`,
//! not `UbuntuSans-CondensedBold`.

use babelfont::{Font, FormatSpecific, Instance};
use serde_json::Value;

/// Glyphs' per-instance `exports` flag.
const KEY_GLYPHS_EXPORTS: &str = "com.schriftgestalt.Glyphs.exports";

/// Glyphs' custom parameters are kept under this prefix.
const KEY_GLYPHS_CUSTOM_PARAMETER_PREFIX: &str = "com.schriftgestalt.Glyphs.customParameters.";

/// babelfont has nowhere to keep a UFO's styleName but its format-specific map.
const KEY_UFO_STYLE_NAME: &str = "ufo.styleName";

/// Whether this instance should produce a static font.
///
/// Glyphs instances can be marked as not for export, and instances of kind
/// "variable" stand for a variable font rather than a static. Neither appears in
/// the designspace glyphsLib produces, so the Python builder never builds them.
pub(crate) fn should_build_static(instance: &Instance) -> bool {
    if instance.variable {
        return false;
    }
    // Instances are exported unless explicitly marked otherwise.
    instance
        .format_specific
        .get(KEY_GLYPHS_EXPORTS)
        .and_then(Value::as_bool)
        .unwrap_or(true)
}

/// The base name of the static font built from `instance`: `FamilyStyle`, with
/// spaces removed, and with no directory or extension.
pub(crate) fn static_base_name(source: &Font, instance: &Instance) -> String {
    // An explicit `fileName` custom parameter is the source author telling us
    // exactly what to call the font. It is how instances which vary on an axis
    // other than weight name themselves.
    if let Some(stem) = enabled_custom_parameter(&instance.format_specific, "fileName")
        .and_then(Value::as_str)
        .and_then(|file_name| std::path::Path::new(file_name).file_stem())
        .map(|stem| stem.to_string_lossy().to_string())
    {
        return stem;
    }

    let family = family_name(source, instance);
    let style = without_redundant_family_words(&family, &style_name(source, instance, &family));
    format!("{family}-{style}").replace(' ', "")
}

/// A stand-in instance for a source which declares no instances of its own: the
/// source *is* the static font, so it takes its own style name.
pub(crate) fn default_instance(source: &Font) -> Instance {
    let style = source_style_name(source).unwrap_or_else(|| "Regular".to_string());
    Instance {
        name: (&style).into(),
        ..Default::default()
    }
}

fn family_name(source: &Font, instance: &Instance) -> String {
    instance
        .custom_names
        .family_name
        .get_default()
        .map(ToString::to_string)
        .or_else(|| {
            source
                .names
                .family_name
                .get_default_or_fallback()
                .map(ToString::to_string)
        })
        .unwrap_or_else(|| "Unknown".to_string())
}

fn style_name(source: &Font, instance: &Instance, family: &str) -> String {
    if let Some(preferred_subfamily_name) =
        instance.custom_names.preferred_subfamily_name.get_default()
    {
        return preferred_subfamily_name.to_string();
    }
    if let Some(instance_name) = instance.name.get_default_or_fallback() {
        // Glyphs instance names are "<family> <style>"; drop the family part.
        let style = instance_name.to_string().replace(&format!("{family} "), "");
        if !style.trim().is_empty() {
            return style;
        }
    }
    source_style_name(source).unwrap_or_else(|| "Regular".to_string())
}

/// The style name of a source which has no instances of its own, such as a bare
/// UFO.
fn source_style_name(source: &Font) -> Option<String> {
    source
        .names
        .preferred_subfamily_name
        .get_default()
        .map(ToString::to_string)
        .or_else(|| {
            source
                .format_specific
                .get(KEY_UFO_STYLE_NAME)
                .and_then(Value::as_str)
                .map(ToString::to_string)
        })
        .or_else(|| {
            source
                .names
                .wws_subfamily_name
                .get_default()
                .map(ToString::to_string)
        })
}

/// A style name should not repeat words which are already in the family name:
/// `Ubuntu Sans Condensed` + `Condensed Thin` is just `UbuntuSansCondensed-Thin`.
fn without_redundant_family_words(family: &str, style: &str) -> String {
    let family_words = family.split_whitespace().collect::<Vec<_>>();
    let mut style_words = style.split_whitespace().collect::<Vec<_>>();
    while style_words.len() > 1 && family_words.contains(&style_words[0]) {
        style_words.remove(0);
    }
    style_words.join(" ")
}

/// The value of an enabled Glyphs custom parameter, mirroring babelfont's own
/// `enabled_cp_value`. Custom parameters are stored as
/// `{"value": ..., "disabled": ...}` objects under a prefixed key.
fn enabled_custom_parameter<'a>(
    format_specific: &'a FormatSpecific,
    name: &str,
) -> Option<&'a Value> {
    let wrapper = format_specific
        .get(&format!("{KEY_GLYPHS_CUSTOM_PARAMETER_PREFIX}{name}"))?
        .as_object()?;
    if wrapper
        .get("disabled")
        .and_then(Value::as_bool)
        .unwrap_or(false)
    {
        return None;
    }
    wrapper.get("value")
}
