[package]
name = "gftools"
description = "Font manipulation library used by Google Fonts"
version = "0.1.0-alpha"
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
skrifa = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
toml = { workspace = true }
serde_json_path_to_error = { workspace = true }
write-fonts = { workspace = true, features = ["tables"] }
linesweeper = { workspace = true }
gf-metadata = { workspace = true }
protobuf = { workspace = true }
fontspector-hotfix = { workspace = true }
kurbo = { workspace = true }
gix = { workspace = true }
pretty_assertions.workspace = true
google-fonts-languages = "0.7.11"
google-fonts-axisregistry = { workspace = true }
unicode-script = "0.5.8"
regex = "1.13.1"
chrono.workspace = true

[dev-dependencies]
serde_yaml_ng = { workspace = true }

[lints.clippy]
result_large_err = "allow"
